### ISSUE TITLE
Connection succesful but query returens invalid data

### ISSUE THREAD

**Issue by adrian-cepeda** [128technology/grafana-datasource#5]
Hi,

Im testing T128 version 3.1.2 and trying to get some graphs using grafana version 4.5.2-1.
When I test the connection I get this "Connection successful but query returned invalid data"
What I can see in the post GET and PUT send JSON and the POST sends back HTLM.

Can you shed some light or point me in the direction to solve this issue?

**Comment by rsitzman** [comment]
It looks like PR #4 adds support for 3.1.x but hasn't been merged yet. You may want to try out the [influx-importer](https://github.com/128technology/influx-importer) project as an alternative.

**Comment by thedillonb** [comment]
@adrian-cepeda PR #4 has been merged. You can try the latest release (https://github.com/128technology/grafana-datasource/releases/tag/v1.1) as there are substantial improvements.

**Comment by thedillonb** [comment]
Closing this as this problem should be resolved in the latest release.
